language: cpp
sudo: true
install: true

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: never

arch: amd64

jobs:
  include:
    - os: linux
      dist: focal
    - os: osx
      osx_image: xcode12.2

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libsdl2-2.0-0
      - libsdl2-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install sdl2; fi

script:
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -Bbuild -H.
  - cd build
  - make all